version: '{branch}.{build}'
configuration: Debug
platform:
- x86
- x64
init:
- cmd: >-
    setlocal EnableDelayedExpansion

    echo [INFO] Reading release notes from %APPVEYOR_BUILD_FOLDER%\newReleaseNotes.md...

    set "releasenotescontent="

    for /F "delims=" %%a in (%APPVEYOR_BUILD_FOLDER%\newReleaseNotes.md) do set "releasenotescontent=!releasenotescontent!\n%%a"

    set "releasenotescontent=!releasenotescontent:~2!"
before_build:
- ps: nuget restore
build:
  project: 3P.sln
  verbosity: minimal
after_build:
- cmd: echo $(releasenotescontent)
artifacts:
- path: Releases\3P.zip
  name: 3P.zip
- path: Releases\3P_x64.zip
  name: 3P_x64.zip
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(releasenotescontent)
  auth_token:
    secure: xE+f8rczPCfechI3U6gncyX2HWWVXN96l6RQ+XlVrWo+0YKf32phrXSzQ6WYEGEs
  artifact: Releases\3P.zip,Releases\3P_x64.zip
  draft: true
  prerelease: true
  force_update: false
  on:
    APPVEYOR_REPO_TAG: TRUE
notifications:
- provider: Email
  to:
  - greenzest@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false