version: '{branch}.{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: 3P.sln
  verbosity: minimal
artifacts:
- path: Releases\3P.zip
  name: 3P.zip
- path: Releases\3P_x64.zip
  name: 3P_x64.zip
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: Copy the content of NEXT_RELEASE_NOTES.md here :)
  # https://ci.appveyor.com/tools/encrypt
  auth_token:
    secure: F3cm5vwqQUGAClxzUV2Z2ltmQtRyDJLQalZ3lC0CUkxA6N4AGmNu1Bf4DKgmXXzU
  artifact: Releases\3P.zip,Releases\3P_x64.zip
  draft: true
  prerelease: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
notifications:
- provider: Email
  to:
  - greenzest@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false