version: '{branch}.{build}'
configuration: Debug
platform:
- x86
- x64
before_build:
- ps: nuget restore
build:
  project: 3P.sln
  verbosity: minimal
artifacts:
- path: Releases\3P.zip
  name: 3P.zip
- path: Releases\3P_x64.zip
  name: 3P_x64.zip
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: ???
  auth_token:
    secure: xE+f8rczPCfechI3U6gncyX2HWWVXN96l6RQ+XlVrWo+0YKf32phrXSzQ6WYEGEs
  artifact: Releases\3P.zip,Releases\3P_x64.zip
  draft: true
  prerelease: true
  force_update: false
  on:
    APPVEYOR_REPO_TAG: TRUE