version: '{branch}.{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: nuget restore -recursive
build:
  project: 3P.sln
  verbosity: minimal
artifacts:
- path: Releases\3P.zip
  name: 3P.zip
- path: Releases\3P_x64.zip
  name: 3P_x64.zip
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: Copy the content of NEXT_RELEASE_NOTES.md here :)
  auth_token:
    secure: xE+f8rczPCfechI3U6gncyX2HWWVXN96l6RQ+XlVrWo+0YKf32phrXSzQ6WYEGEs
  artifact: Releases\3P.zip,Releases\3P_x64.zip
  draft: true
  prerelease: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
notifications:
- provider: Email
  to:
  - greenzest@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false